swg++453 -fPIC -O3 -c /home/export/online1/systest/swrh/lhb/UNAT/test/multiLevelBlock/test.cpp -o /home/export/online1/systest/swrh/lhb/UNAT/test/multiLevelBlock/test.o -I/home/export/online1/systest/swrh/lhb/UNAT/topology/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/ -I/home/export/online1/systest/swrh/lhb/UNAT/ -I/home/export/online1/systest/swrh/lhb/UNAT/RL_MPI/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/ -I/home/export/online1/systest/swrh/lhb/UNAT/tools/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/vertex2EdgeIter/
sw5cc -host -fPIC -O3 -c /home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/edge2VertexIter_host.c -o /home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/edge2VertexIter_host.o -I/home/export/online1/systest/swrh/lhb/UNAT/topology/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/ -I/home/export/online1/systest/swrh/lhb/UNAT/ -I/home/export/online1/systest/swrh/lhb/UNAT/RL_MPI/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/ -I/home/export/online1/systest/swrh/lhb/UNAT/tools/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/vertex2EdgeIter/
sw5cc -host -fPIC -O3 -c /home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/vertex2EdgeIter/vertex2EdgeIter_host.c -o /home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/vertex2EdgeIter/vertex2EdgeIter_host.o -I/home/export/online1/systest/swrh/lhb/UNAT/topology/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/ -I/home/export/online1/systest/swrh/lhb/UNAT/ -I/home/export/online1/systest/swrh/lhb/UNAT/RL_MPI/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/ -I/home/export/online1/systest/swrh/lhb/UNAT/tools/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/vertex2EdgeIter/
sw5cc -host -fPIC -O3 -c /home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/funcPointer.c -o /home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/funcPointer.o -I/home/export/online1/systest/swrh/lhb/UNAT/topology/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/ -I/home/export/online1/systest/swrh/lhb/UNAT/ -I/home/export/online1/systest/swrh/lhb/UNAT/RL_MPI/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/ -I/home/export/online1/systest/swrh/lhb/UNAT/tools/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/vertex2EdgeIter/
/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/funcPointer.c: In function 'funcPointer_slave':
/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/funcPointer.c:29: warning: return from incompatible pointer type
/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/funcPointer.c:31: warning: return from incompatible pointer type
sw5cc -host -fPIC -O3 -c /home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/userFunc_host.c -o /home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/userFunc_host.o -I/home/export/online1/systest/swrh/lhb/UNAT/topology/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/ -I/home/export/online1/systest/swrh/lhb/UNAT/ -I/home/export/online1/systest/swrh/lhb/UNAT/RL_MPI/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/ -I/home/export/online1/systest/swrh/lhb/UNAT/tools/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/vertex2EdgeIter/
sw5cc -host -fPIC -O3 -c /home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/BlockOrdering/BlockOrdering.c -o /home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/BlockOrdering/BlockOrdering.o -I/home/export/online1/systest/swrh/lhb/UNAT/topology/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/ -I/home/export/online1/systest/swrh/lhb/UNAT/ -I/home/export/online1/systest/swrh/lhb/UNAT/RL_MPI/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/ -I/home/export/online1/systest/swrh/lhb/UNAT/tools/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/vertex2EdgeIter/
sw5cc -host -fPIC -O3 -c /home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/BlockOrdering/BOrderUtils.c -o /home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/BlockOrdering/BOrderUtils.o -I/home/export/online1/systest/swrh/lhb/UNAT/topology/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/ -I/home/export/online1/systest/swrh/lhb/UNAT/ -I/home/export/online1/systest/swrh/lhb/UNAT/RL_MPI/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/ -I/home/export/online1/systest/swrh/lhb/UNAT/tools/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/vertex2EdgeIter/
sw5cc -host -fPIC -O3 -c /home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/extensibleArray/extensibleLabelArray.c -o /home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/extensibleArray/extensibleLabelArray.o -I/home/export/online1/systest/swrh/lhb/UNAT/topology/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/ -I/home/export/online1/systest/swrh/lhb/UNAT/ -I/home/export/online1/systest/swrh/lhb/UNAT/RL_MPI/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/ -I/home/export/online1/systest/swrh/lhb/UNAT/tools/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/vertex2EdgeIter/
sw5cc -host -fPIC -O3 -c /home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/extensibleArray/extensibleScalarArray.c -o /home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/extensibleArray/extensibleScalarArray.o -I/home/export/online1/systest/swrh/lhb/UNAT/topology/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/ -I/home/export/online1/systest/swrh/lhb/UNAT/ -I/home/export/online1/systest/swrh/lhb/UNAT/RL_MPI/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/ -I/home/export/online1/systest/swrh/lhb/UNAT/tools/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/vertex2EdgeIter/
sw5cc -slave -fPIC -msimd -O3 -c /home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/edge2VertexIter_slave.c -o /home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/edge2VertexIter_slave.o -I/home/export/online1/systest/swrh/lhb/UNAT/topology/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/ -I/home/export/online1/systest/swrh/lhb/UNAT/ -I/home/export/online1/systest/swrh/lhb/UNAT/RL_MPI/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/ -I/home/export/online1/systest/swrh/lhb/UNAT/tools/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/vertex2EdgeIter/
/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/edge2VertexIter_slave.c: In function 'func':
/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/edge2VertexIter_slave.c:70: warning: initialization discards qualifiers from pointer target type
/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/edge2VertexIter_slave.c:70: warning: initialization discards qualifiers from pointer target type
/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/edge2VertexIter_slave.c:71: warning: initialization discards qualifiers from pointer target type
/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/edge2VertexIter_slave.c:72: warning: initialization discards qualifiers from pointer target type
/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/edge2VertexIter_slave.c:72: warning: initialization discards qualifiers from pointer target type
/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/edge2VertexIter_slave.c:73: warning: initialization discards qualifiers from pointer target type
/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/edge2VertexIter_slave.c:74: warning: initialization discards qualifiers from pointer target type
/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/edge2VertexIter_slave.c:75: warning: initialization discards qualifiers from pointer target type
/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/edge2VertexIter_slave.c:75: warning: initialization discards qualifiers from pointer target type
/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/edge2VertexIter_slave.c:75: warning: initialization discards qualifiers from pointer target type
sw5cc -slave -fPIC -msimd -O3 -c /home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/userFunc_slave.c -o /home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/userFunc_slave.o -I/home/export/online1/systest/swrh/lhb/UNAT/topology/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/ -I/home/export/online1/systest/swrh/lhb/UNAT/ -I/home/export/online1/systest/swrh/lhb/UNAT/RL_MPI/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/ -I/home/export/online1/systest/swrh/lhb/UNAT/tools/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/vertex2EdgeIter/
sw5cc -host -O3 -c /home/export/online1/systest/swrh/lhb/UNAT/RL_MPI/register.C -o /home/export/online1/systest/swrh/lhb/UNAT/RL_MPI/register.o -I/home/export/online1/systest/swrh/lhb/UNAT/topology/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/ -I/home/export/online1/systest/swrh/lhb/UNAT/ -I/home/export/online1/systest/swrh/lhb/UNAT/RL_MPI/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/ -I/home/export/online1/systest/swrh/lhb/UNAT/tools/ -I/home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/vertex2EdgeIter/
sw5cc -slave -fPIC -msimd -g -c /home/export/online1/systest/swrh/lhb/UNAT/tools/slaveUtils.c -o /home/export/online1/systest/swrh/lhb/UNAT/tools/slaveUtils.o 
/home/export/online1/systest/swrh/lhb/UNAT/tools/slaveUtils.c: In function 'DMA_Get':
/home/export/online1/systest/swrh/lhb/UNAT/tools/slaveUtils.c:7: warning: passing argument 2 of 'dma_set_reply' from incompatible pointer type
/home/export/online1/systest/swrh/lhb/UNAT/tools/slaveUtils.c:8: warning: passing argument 2 of '__builtin_sw64_dma' makes integer from pointer without a cast
/home/export/online1/systest/swrh/lhb/UNAT/tools/slaveUtils.c:8: warning: passing argument 3 of '__builtin_sw64_dma' makes integer from pointer without a cast
/home/export/online1/systest/swrh/lhb/UNAT/tools/slaveUtils.c:9: warning: passing argument 1 of 'dma_wait' from incompatible pointer type
/home/export/online1/systest/swrh/lhb/UNAT/tools/slaveUtils.c: In function 'DMA_IGet':
/home/export/online1/systest/swrh/lhb/UNAT/tools/slaveUtils.c:16: warning: passing argument 2 of 'dma_set_reply' from incompatible pointer type
/home/export/online1/systest/swrh/lhb/UNAT/tools/slaveUtils.c:17: warning: passing argument 2 of '__builtin_sw64_dma' makes integer from pointer without a cast
/home/export/online1/systest/swrh/lhb/UNAT/tools/slaveUtils.c:17: warning: passing argument 3 of '__builtin_sw64_dma' makes integer from pointer without a cast
/home/export/online1/systest/swrh/lhb/UNAT/tools/slaveUtils.c: In function 'DMA_Put':
/home/export/online1/systest/swrh/lhb/UNAT/tools/slaveUtils.c:24: warning: passing argument 2 of 'dma_set_reply' from incompatible pointer type
/home/export/online1/systest/swrh/lhb/UNAT/tools/slaveUtils.c:25: warning: passing argument 2 of '__builtin_sw64_dma' makes integer from pointer without a cast
/home/export/online1/systest/swrh/lhb/UNAT/tools/slaveUtils.c:25: warning: passing argument 3 of '__builtin_sw64_dma' makes integer from pointer without a cast
/home/export/online1/systest/swrh/lhb/UNAT/tools/slaveUtils.c:26: warning: passing argument 1 of 'dma_wait' from incompatible pointer type
/home/export/online1/systest/swrh/lhb/UNAT/tools/slaveUtils.c: In function 'DMA_IPut':
/home/export/online1/systest/swrh/lhb/UNAT/tools/slaveUtils.c:33: warning: passing argument 2 of 'dma_set_reply' from incompatible pointer type
/home/export/online1/systest/swrh/lhb/UNAT/tools/slaveUtils.c:34: warning: passing argument 2 of '__builtin_sw64_dma' makes integer from pointer without a cast
/home/export/online1/systest/swrh/lhb/UNAT/tools/slaveUtils.c:34: warning: passing argument 3 of '__builtin_sw64_dma' makes integer from pointer without a cast
/home/export/online1/systest/swrh/lhb/UNAT/tools/slaveUtils.c: In function 'DMA_Wait':
/home/export/online1/systest/swrh/lhb/UNAT/tools/slaveUtils.c:39: warning: passing argument 1 of 'dma_wait' from incompatible pointer type
swld453 -hybrid /home/export/online1/systest/swrh/lhb/UNAT/test/multiLevelBlock/test.o /home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/edge2VertexIter_host.o /home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/vertex2EdgeIter/vertex2EdgeIter_host.o /home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/funcPointer.o /home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/userFunc_host.o /home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/BlockOrdering/BlockOrdering.o /home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/BlockOrdering/BOrderUtils.o /home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/extensibleArray/extensibleLabelArray.o /home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/extensibleArray/extensibleScalarArray.o /home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/edge2VertexIter_slave.o /home/export/online1/systest/swrh/lhb/UNAT/iterator/multiLevelBlockIterator/edge2VertexIter/userFunc_slave.o /home/export/online1/systest/swrh/lhb/UNAT/RL_MPI/register.o /home/export/online1/systest/swrh/lhb/UNAT/tools/slaveUtils.o -o a.out -lm -lstdc++ -L/home/export/online1/systest/swrh/lhb/UNAT/lib/LIB_SW -lmetis -lrlmpi
/usr/sw-mpp/bin/sw5ld: Warning: size of symbol `slave_athread_wait' changed from 72 in /home/export/online1/systest/swrh/lhb/UNAT/tools/slaveUtils.o to 48 in /usr/sw-mpp/swcc/sw5gcc-binary/sw_64thl-unknown-linux-gnu/lib/libslave.a(slave_dma.o)
